### ISSUE TITLE
Support OpenAPI 3.1.0

### ISSUE THREAD

**Issue by simplesmiler** [simplesmiler/taxios#18]
### Motivation
- Upcoming release of Swagger v4, with both UI and Editor supporting OpenAPI 3.1.0
- OpenAPI 3.1.0 introduces a proper `null` type, which nicely maps to TypeScript `null` type. Prior to 3.1.0 there was `nullable` field, but it is very inconvenient at times, e.g. https://github.com/OAI/OpenAPI-Specification/issues/1368

Spec: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md and https://spec.openapis.org/oas/v3.1.0
3.0 -> 3.1: https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

Blockers:
- [x] https://github.com/APIDevTools/swagger-parser/issues/169 and https://github.com/zaggino/z-schema/issues/268, we use that to fetch, validate and parse
  - Fixed upstream, z-schema is not relevant anymore.
- [ ] swagger2openapi, we use that to convert to the latest version (currently 2.x -> 3.0) to simplify further processing. 
  - Not really a blocker for 3.1.

**Comment by crutch12** [comment]
Waiting for https://github.com/Mermade/oas-kit/issues/529

**Comment by simplesmiler** [comment]
https://github.com/APIDevTools/swagger-parser/pull/187 landed in `10.1.0`, so parser stopped complaining.

**Comment by simplesmiler** [comment]
In that PR `z-schema` was replaced with `ajv`, so it's not a blocker anymore.

**Comment by simplesmiler** [comment]
`swagger2openapi` and `oas-kit` issues seem to be related to up-conversion to 3.1 (e.g. https://github.com/simplesmiler/taxios/issues/25) rather than being blockers to 3.1 support.

**Comment by simplesmiler** [comment]
Committed `@apidevtools/swagger-parser@^10.1.0` to the `0.2.x` and `master` branches.
With this, OpenAPI 3.1 is supported in principle, and this issue can be closed.

If there are specific problems with specific examples, they can be tackled in specific issues.
