### ISSUE TITLE
Attribute "nullable" from OpenAPI 3.0 does not work

### ISSUE THREAD

**Issue by simplesmiler** [simplesmiler/taxios#25]
Current state: 
- JSONSchema, even from [ye olden days](https://json-schema.org/specification-links.html), always had a proper **null type**.
- OpenAPI 3.0 [dialect of JSONSchema](https://swagger.io/docs/specification/data-models/keywords/) forbids the use of **null type** and introduces **nullable** attribute  instead.
- OpenAPI 3.1 [dialect](https://spec.openapis.org/oas/v3.1.0#schema-object) aligns with JSONSchema more closely, [deprecating](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0) the **nullable** attribute, and bringing back the **null type**.
- Library used by Taxios to convert JSONSchema to TypeScript knows nothing about the dialect and happily ignores **nullable** attribute. Thus, Taxios generates wrong TypeScript for faithful OpenAPI 3.0 documents.
- This could be mitigated by using hybrid documents, which are declared as OpenAPI 3.0 but actually use standard JSONSchema instead of the dialect. Although such hybrid documents do not pass validation, and have issues with the authoring tools (e.g. Stoplight reads hybrid documents properly, but converts edited sections back to the dialect).
- OpenAPI 3.1 is still quite new, and is not supported yet in many places, so Taxios users may be forced to stick with OpenAPI 3.0.

The issue can be fixed by doing yet another pre-pass on the schema before feeding it to TS generator, to convert every **nullable** attribute into proper JSONSchema **null type**.

**Comment by simplesmiler** [comment]
Waiting on swagger2openapi (https://github.com/Mermade/oas-kit/issues/529).

Or for a different package that can convert * -> 3.1.

**Comment by JaredCE** [comment]
Hey hey, wonder if this library would help you: https://github.com/openapi-contrib/openapi-schema-to-json-schema it converts openAPI schemas to JSON Schema draft 04

**Comment by simplesmiler** [comment]
> Hey hey, wonder if this library would help you: https://github.com/openapi-contrib/openapi-schema-to-json-schema it converts openAPI schemas to JSON Schema draft 04

Committed in 0.3.0-alpha.1, will be included in 0.3.0 release. Kudos!
