### ISSUE TITLE
в npm лежит не последняя версия taxios

### ISSUE THREAD

**Issue by TakumiFuji** [simplesmiler/taxios#27]
До сих пор ругается на версию axios  выше 0.21.0

**Comment by TakumiFuji** [comment]
I would be very grateful if you upload the latest version to npm

**Comment by crutch12** [comment]
Quick fix:
`npm i @simplesmiler/taxios --force`

**Comment by TakumiFuji** [comment]
When will you update?

**Comment by simplesmiler** [comment]
Currently master branch contains other changes that I didn't want to release until 0.3.0.

But because the peer dep change issue is the most offending, I cherry-picked it to the 0.2.x support branch and published as 0.2.12.
