### ISSUE TITLE
minItems/maxItems causes out of memory error

### ISSUE THREAD

**Issue by crutch12** [simplesmiler/taxios#33]
Array Length:
https://swagger.io/docs/specification/data-models/data-types/#array

**Problem**

Generator takes `maxItems` length and generates too long array:
```
[1] | [1, 2] | [1, 2, 3] | ...
```

So node fails with **out of memory** error

**Comment by simplesmiler** [comment]
Fixed:
- Published 0.2.14 with support for `--ignore-min-max-items` flag, see #30.
- Bumped json-schema-to-typescript version in master, see https://github.com/bcherny/json-schema-to-typescript/issues/438.
